Create database TuneVault_DB
CREATE TABLE ApplicationUsers (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    UserName NVARCHAR,
    Email NVARCHAR,
    PasswordHash NVARCHAR,
    Bio NVARCHAR,
    AvatarPath NVARCHAR,
    CreatedAt DATETIME
);

CREATE TABLE Albums (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Title NVARCHAR,
    CoverImageUrl NVARCHAR,
    ReleaseDate DATETIME,
    OwnerId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES AppUsers(Id)
);

CREATE TABLE MediaItems (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Title NVARCHAR,
    Description NVARCHAR,
    MediaType INT,
    Duration INT,
    FilePath NVARCHAR,
    ThumbnailPath NVARCHAR,
    IsPublic BIT,
    OwnerId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES AppUsers(Id),
    AlbumId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Albums(Id),
    CreatedAt DATETIME
);

CREATE TABLE Playlists (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Title NVARCHAR,
    Description NVARCHAR,
    CoverImageUrl NVARCHAR,
    IsPublic BIT,
    UserId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES AppUsers(Id),
    CreatedAt DATETIME
);

CREATE TABLE PlaylistTracks (
    PlaylistId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Playlists(Id),
    MediaItemId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES MediaItems(Id),
    AddedAt DATETIME,
    PRIMARY KEY (PlaylistId, MediaItemId)
);

CREATE TABLE Favorites (
    UserId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES AppUsers(Id),
    MediaItemId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES MediaItems(Id),
    CreatedAt DATETIME,
    PRIMARY KEY (UserId, MediaItemId)
);

CREATE TABLE PlayHistories (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    UserId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES AppUsers(Id),
    MediaItemId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES MediaItems(Id),
    PlayedAt DATETIME
);

CREATE TABLE Follows (
    FollowerId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES AppUsers(Id),
    FolloweeId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES AppUsers(Id),
    CreatedAt DATETIME,
    PRIMARY KEY (FollowerId, FolloweeId)
);

CREATE TABLE MediaShares (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    SenderId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES AppUsers(Id),
    ReceiverId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES AppUsers(Id),
    MediaItemId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES MediaItems(Id),
    PlaylistId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Playlists(Id),
    Message NVARCHAR,
    SharedAt DATETIME
);

CREATE TABLE Notifications (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    UserId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES AppUsers(Id),
    Type INT,
    Payload NVARCHAR,
    IsRead BIT,
    CreatedAt DATETIME
);

CREATE TABLE MediaTags (
    MediaItemId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES MediaItems(Id),
    TagName NVARCHAR,
    PRIMARY KEY (MediaItemId, TagName)
);